shrimp/stories/models.py
from dataclasses import dataclass
from datetime import datetime
from shrimp.utils.db import Model


@dataclass
class Story:
    id: int
    title: str
    link: str
    description: str
    date_posted: datetime
    username: str


@dataclass
class Comment:
    id: int
    body: str
    date_posted: datetime
    username: str


class StoryModel(Model):
    def insert(self, title: str, link: str, description: str, account_id: int) -> int:
        cursor = self.db.execute(
            """
            INSERT INTO Stories (title, link, description, account_id)
                VALUES (?, ?, ?, ?)
            """,
            (title, link, description, account_id),
        )
        self.db.commit()

        id = cursor.lastrowid
        if not id:
            raise RuntimeError("insert failed: no lastrowid")

        return id

    def get(self, id: int) -> Story:
        row = self.db.execute(
            """
            SELECT Stories.id, title, link, description, date_posted, Accounts.username
            FROM Stories
            JOIN Accounts ON Stories.account_id = Accounts.id
            WHERE Stories.id = ?
            """,
            (id,),
        ).fetchone()

        if not row:
            raise RuntimeError(f"Story with id {id} not found")

        return Story(*row)

    def get_by_link(self, link: str) -> Story:
        cursor = self.db.execute(
            """
            SELECT * 
            FROM stories 
            WHERE link = ?
            """,
            (link,),
        )

        return cursor.fetchone()

    def account_stories(self, account_id: int) -> list[Story]:
        stories = self.db.execute(
            """
            SELECT Stories.id, title, link, description, date_posted, Accounts.username
            FROM Stories, Accounts
            WHERE Stories.account_id = Accounts.id
                AND Accounts.id = ?
            """,
            (account_id,),
        )
        return [Story(*s) for s in stories]

    def latest(self) -> list[Story]:
        rows = self.db.execute(
            """
            SELECT Stories.id, title, link, description, date_posted, Accounts.username
            FROM Stories
            JOIN Accounts ON Stories.account_id = Accounts.id
            ORDER BY date_posted DESC
            LIMIT 10
            """
        ).fetchall()

        return [Story(*row) for row in rows]


class CommentModel(Model):
    def insert(self, body: str, story_id: int, account_id: int) -> int:
        cursor = self.db.execute(
            """
            INSERT INTO comment (body, story_id, account_id)
            VALUES (?, ?, ?)
            """,
            (body, story_id, account_id),
        )
        self.db.commit()

        id = cursor.lastrowid
        if not id:
            raise RuntimeError("insert failed: no lastrowid")

        return id

    def account_comments(self, account_id: int) -> list[Comment]:
        comments = self.db.execute(
            """
            SELECT comment.id, comment.body, comment.date_posted
            FROM comment, Accounts
            JOIN Accounts ON comment.account_id = Accounts.id
            WHERE comment.account_id = Accounts.id
                AND Accounts.id = ?
            """,
            (account_id,),
        )
        return [Comment(*s) for s in comments]

    def comments_for_story(self, story_id: int) -> list[Comment]:
        rows = self.db.execute(
            """
            SELECT comment.id, comment.body, comment.date_posted, Accounts.username
            FROM comment
            JOIN Accounts ON comment.account_id = Accounts.id
            WHERE comment.story_id = ?
            ORDER BY comment.date_posted DESC
            """,
            (story_id,),
        )
        return [Comment(*row) for row in rows]

shrimp/stories/forms.py
from dataclasses import dataclass

from shrimp.utils.forms import Form


@dataclass
class StoriesCreateForm(Form):
    title: str = ""
    link: str = ""
    description: str = ""
    username: str = ""


@dataclass
class CommentForm(Form):
    body: str = ""
    username: str = ""

shrimp/stories/__init__.py
from flask import Blueprint

blueprint = Blueprint("stories", __name__, url_prefix="/stories")


from shrimp.stories import routes

shrimp/stories/routes.py
from flask import redirect, render_template, url_for, request, flash, session
from re import match

from shrimp.stories import blueprint, forms
from shrimp.stories.models import StoryModel, CommentModel
from shrimp.utils import db
from shrimp.utils.forms import Field
from shrimp.stories.forms import CommentForm


@blueprint.get("/")
def index():
    story_model = StoryModel(db.get_connection())
    stories = story_model.latest()

    return render_template("/stories/index.jinja", stories=stories)


@blueprint.get("/create")
def create():
    account_id = session.get("account_id")
    if account_id is None:
        flash("You must be logged in to be able to submit a story.")
        return redirect(url_for("accounts.login"))

    form = forms.StoriesCreateForm()
    return render_template("/stories/create.jinja", form=form)


@blueprint.post("/create")
def create_submit():
    account_id = session.get("account_id")
    if account_id is None:
        return redirect(url_for("accounts.login"))

    title = request.form["title"]
    link = request.form["link"]
    description = request.form["description"]

    form = forms.StoriesCreateForm(title, link, description)
    stories = StoryModel(db.get_connection())

    form.check_field(Field.not_blank(form.title), "title", "This field cannot be blank")
    form.check_field(
        Field.max_chars(form.title, 80),
        "title",
        "This field cannot be more than 80 characters long",
    )

    form.check_field(Field.not_blank(form.link), "link", "This field cannot be blank")
    form.check_field(
        Field.unique_value(link, lambda link: stories.get_by_link(link) is not None),
        "link",
        "This link has already been submitted.",
    )

    if not form.is_valid:
        return render_template("stories/create.jinja", form=form), 422

    story_id = stories.insert(form.title, form.link, form.description, int(account_id))

    flash("Story added successfully!")

    return redirect(url_for("stories.story_show", story_id=story_id))


@blueprint.get("/<int:story_id>", endpoint="story_show")
def story_show(story_id):
    story_model = StoryModel(db.get_connection())
    comment_model = CommentModel(db.get_connection())

    story = story_model.get(story_id)
    comments = comment_model.comments_for_story(story_id)

    form = forms.CommentForm()

    return render_template(
        "stories/description.jinja", story=story, comments=comments, form=form
    )


@blueprint.post("/<int:story_id>")
def submit_comment(story_id):
    account_id = session.get("account_id")

    if account_id is None:
        flash("You must be logged in to be able to comment.")
        return redirect(url_for("accounts.login"))

    body = request.form["body"]

    form = forms.CommentForm(body)

    form.check_field(Field.not_blank(form.body), "body", "This field cannot be blank")
    form.check_field(
        Field.max_chars(form.body, 10000),
        "body",
        "Comment is too long (max 10,000 characters)",
    )

    story_model = StoryModel(db.get_connection())
    comment_model = CommentModel(db.get_connection())

    if not form.is_valid:
        story = story_model.get(story_id)
        comments = comment_model.comments_for_story(story_id)

        return render_template(
            "stories/description.jinja", story=story, comments=comments, form=form
        ), 422

    comment_model.insert(body, story_id, int(account_id))

    flash("Comment submitted successfully.")
    return redirect(url_for("stories.story_show", story_id=story_id))

shrimp/templates/stories/create.jinja
{% extends "base.jinja" %}
{% block title %}Submit a new story{% endblock %}

{% block content %}
    <h1>Submit a Story</h1>

    <form method="post" class="story-form">
        <label for="title"> 
            Title
            <input type="text" name="title" value="{{ form.title }}" />
        </label>
        {% if form.field_errors.title %}
            <div class="error">{{ form.field_errors.title }}</div>
        {% endif %}

        <label for="link">
            Link
            <input type="text" name="link" value="{{ form.link }}" />
        </label>
        {% if form.field_errors.link %}
            <div class="error">{{ form.field_errors.link }}</div>
        {% endif %}

        <label for="description">
            Description
            <textarea name="description" rows="5">{{ form.description }}</textarea>    
        </label>
        

        <button type="submit">Submit</button>
    </form>
{% endblock %}

shrimp/templates/stories/description.jinja
{% extends "base.jinja" %}
{% block title %}{{ story.title }}{% endblock %}

{% block content %}
    <article class="story">
        <h1 class="story-title">
            <a class="story-link" href="{{ story.link }}">{{ story.title }}</a>
        </h1>
        <p class="story-description">{{ story.description }}</p>

        <p><em>Posted by {{ story.username }} - ({{ story.date_posted|time_ago }})</em></p>
    </article>

    <section class="comment-section">
        <h2>Comments</h2>

        {% if comments %}
            {% for comment in comments %}
                <div class="comment">
                    <strong>{{ comment.username }} - ({{ comment.date_posted|time_ago }})</strong> 
                    <p>{{ comment.body }}</p>
                </div>
            {% endfor %}
        {% else %}
            <p>No comments yet.</p>
        {% endif %}
    </section>

    <section class="comment-form">
        <h3>Leave a Comment</h3>
        <form method="POST" action="{{ url_for('stories.submit_comment', story_id=story.id) }}">
            <label for="body">
                Comment
                <textarea name="body" rows="4">{{ form.body }}</textarea>
            </label>
            {% if form.field_errors.body %}
                <div class="error">{{ form.field_errors.body }}</div>
            {% endif %}

            <button type="submit">Submit</button>
        </form>
    </section>
{% endblock %}

shrimp/templates/stories/index.jinja
{% extends "base.jinja" %}
{% block title %}Shrimp — All stories{% endblock %}

{% block content %}
    <h1>Recent Stories</h1>

    <table class="story-table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Posted By</th>
                <th>Link to Story</th>
                <th>Date posted</th>
            </tr>
        </thead>
        <tbody>
            {% for story in stories %}
                <tr>
                    <td>
                        <a class="story-link" href="{{ url_for('stories.story_show', story_id=story.id) }}">
                            {{ story.title }}
                        </a>
                    </td>
                    <td>{{ story.username }}</td>
                    <td>
                        <a class="story-link" href="{{ story.link }}">
                        {{ story.link }} 
                        </a>
                    </td>    
                    <td>{{ story.date_posted|time_ago }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}