shrimp/accounts/models.py
from dataclasses import dataclass

from werkzeug.security import generate_password_hash, check_password_hash

from shrimp.utils.db import Model
from shrimp.stories.models import Story, StoryModel


@dataclass
class Account:
    id: int
    username: str
    email: str
    password: str
    stories: list[Story]


class InvalidCredentialsError(Exception): ...


class AccountModel(Model):
    def insert(self, username: str, email: str, password: str) -> int:
        cursor = self.db.execute(
            """
            INSERT INTO Accounts (username, email, password)
                VALUES (?, ?, ?)
            """,
            (username, email, generate_password_hash(password)),
        )
        self.db.commit()

        id = cursor.lastrowid
        if not id:
            raise RuntimeError("insert failed: no lastrowid")

        return id

    def get(self, id: int) -> Account:
        username, email, password = self.db.execute(
            "SELECT id, username, email, password FROM Accounts WHERE id = ?", (id,)
        ).fetchone()
        stories = StoryModel(self.db)
        return Account(id, username, email, password, stories.account_stories(id))

    def authenticate(self, email: str, password: str) -> Account:
        account = self.db.execute(
            "SELECT id, username, email, password FROM Accounts WHERE email = ?",
            (email,),
        ).fetchone()

        if account is None or not check_password_hash(account[3], password):
            raise InvalidCredentialsError()

        id, username, email, password = account
        stories = StoryModel(self.db)
        return Account(id, username, email, password, stories.account_stories(id))

    def email_exists(self, email: str) -> bool:
        account = self.db.execute(
            "SELECT * FROM Accounts WHERE email = ?", (email,)
        ).fetchone()
        return account is not None

    def username_exists(self, username: str) -> bool:
        account = self.db.execute(
            "SELECT * FROM Accounts WHERE username = ?", (username,)
        ).fetchone()
        return account is not None

shrimp/accounts/forms.py
from dataclasses import dataclass

from shrimp.utils.forms import Form


@dataclass
class LoginForm(Form):
    email: str = ""
    password: str = ""


@dataclass
class AccountCreateForm(Form):
    username: str = ""
    email: str = ""
    password: str = ""

shrimp/accounts/__init__.py
from flask import Blueprint

blueprint = Blueprint("accounts", __name__, url_prefix="/accounts")

from shrimp.accounts import routes

shrimp/accounts/routes.py
from flask import redirect, render_template, url_for, request, flash, session

from shrimp.accounts import blueprint, forms
from shrimp.accounts.models import AccountModel, InvalidCredentialsError
from shrimp.utils import db
from shrimp.utils.forms import Field


@blueprint.get("/create")
def create():
    form = forms.AccountCreateForm()
    return render_template("accounts/create.jinja", form=form)


@blueprint.post("/create")
def create_submit():
    username = request.form["username"]
    email = request.form["email"]
    password = request.form["password"]

    form = forms.AccountCreateForm(username=username, email=email, password=password)
    accounts = AccountModel(db.get_connection())

    form.check_field(
        Field.not_blank(form.username), "username", "This field cannot be blank"
    )
    form.check_field(Field.not_blank(form.email), "email", "This field cannot be blank")
    form.check_field(
        Field.is_valid_email(form.email), "email", "This is not a valid email"
    )
    form.check_field(
        not accounts.username_exists(form.username),
        "username",
        "This username already exists",
    )
    form.check_field(
        not accounts.email_exists(form.email),
        "email",
        "This email already exists",
    )
    form.check_field(
        Field.not_blank(form.password), "password", "This field cannot be blank"
    )
    form.check_field(
        Field.min_chars(form.password, 8),
        "password",
        "This field cannot be less than 8 characters long",
    )
    form.check_field(
        Field.max_chars(form.username, 50),
        "password",
        "This field cannot be more than 20 characters long",
    )
    form.check_field(
        Field.max_chars(form.password, 20),
        "password",
        "This field cannot be more than 20 characters long",
    )

    if not form.is_valid:
        return render_template("accounts/create.jinja", form=form), 422

    accounts = AccountModel(db.get_connection())
    accounts.insert(form.username, form.email, form.password)

    flash("Account successfully created!")

    return redirect(url_for("accounts.login"))


@blueprint.get("/login")
def login():
    form = forms.LoginForm()
    return render_template("accounts/login.jinja", form=form)


@blueprint.post("/login")
def login_submit():
    email = request.form["email"]
    password = request.form["password"]

    form = forms.LoginForm(email, password)
    accounts = AccountModel(db.get_connection())

    try:
        account = accounts.authenticate(form.email, form.password)
    except InvalidCredentialsError:
        form.add_non_field_error("Email or password is incorrect")
        return render_template("accounts/login.jinja", form=form)

    session["account_id"] = account.id
    flash("You've successfully logged in!")
    return redirect(url_for("home"))


@blueprint.get("/logout")
def logout():
    session.pop("account_id", None)
    flash("You've successfully logged out!")
    return redirect(url_for("home"))

shrimp/templates/accounts/create.jinja
{% extends "base.jinja" %}
{% block title %}Register a New Account{% endblock %}
{% block content %}
    <h2>Register a New Account</h2>
    <form action="{{ url_for('accounts.create') }}" method="POST">
        <label>
            Username:
            {% if form.field_errors.get("username") %}
                <p class="error">{{ form.field_errors["email"] }}</p>
            {% endif %}
            <input type="text" name="username" value="{{ form.username }}" required>
        </label>

        <label>
            Email:
            {% if form.field_errors.get("email") %}
                <p class="error">{{ form.field_errors["email"] }}</p>
            {% endif %}
            <input type="email" name="email" value="{{ form.email }}" required>
        </label>
        <label>
            Password:
            {% if form.field_errors.get("password") %}
                <p class="error">{{ form.field_errors["password"] }}</p>
            {% endif %}
            <input type="password" name="password" required>
        </label>
        <button>Submit</button>
    </form>

    <p> If you already have account you can <a href="{{ url_for('accounts.login') }}">Login</a> </p>
{% endblock %}

shrimp/templates/accounts/login.jinja
{% extends "base.jinja" %}
{% block title %}Login{% endblock %}
{% block content %}
    <h2>Login</h2>
    <form action="{{ url_for('accounts.login') }}" method="POST">
        {% for error in form.non_field_errors %}
            <p class="error">{{ error }}</p>
        {% endfor %}
        <label>
            Email:
            {% if form.field_errors.get("email") %}
                <p class="error">{{ form.field_errors["email"] }}</p>
            {% endif %}
            <input type="email" name="email" value="{{ form.email }}" required>
        </label>
        <label>
            Password:
            {% if form.field_errors.get("password") %}
                <p class="error">{{ form.field_errors["password"] }}</p>
            {% endif %}
            <input type="password" name="password" required>
        </label>
        <button>Submit</button>
    </form>
{% endblock %}